;;;; test-factorial-quick.lisp
(load "src/vm.lisp")
(load "src/loader.lisp")
(load "src/compiler-simplified.lisp")

(defvar *factorial* '(defun factorial (n) (if (< n 2) 1 (* n (factorial (- n 1))))))
(defvar *code* (compile-lisp-to-mips-simplified *factorial*))

(defun test-fact (n expected)
  (let ((vm (make-new-vm))
        (start-time (get-internal-real-time)))
    (load-code vm *code*)
    (set-register vm :$A0 n)
    (let ((code-start (calculate-code-start vm)))
      (set-register vm :$RA (+ code-start (length *code*))))
    (run-vm vm :max-instructions 10000)
    (let* ((result (get-register vm :$V0))
           (end-time (get-internal-real-time))
           (elapsed (/ (- end-time start-time) internal-time-units-per-second)))
      (if (= result expected)
          (format t "  ✅ factorial(~D) = ~D [~,3F sec]~%" n result elapsed)
          (format t "  ❌ factorial(~D) = ~D (attendu ~D)~%" n result expected)))))

(format t "~%Test factorial:~%")
(test-fact 0 1)
(test-fact 1 1)
(test-fact 2 2)
(test-fact 3 6)
(test-fact 4 24)
(test-fact 5 120)
