;;;; test-closure-nested-debug.lisp
;;;; Tests simplifiés pour comprendre le problème

(load "loader.lisp")
(load "compiler.lisp")
(load "vm.lisp")

(format t "~%=== TESTS CLOSURES IMBRIQUÉES ===~%")

;; Test A: Une seule fonction imbriquée
(format t "~%Test A: (labels ((outer (x) (labels ((inner (y) (* x y))) (inner 3)))) (outer 2))~%")
(let* ((exprA '(labels ((outer (x)
                          (labels ((inner (y)
                                     (* x y)))
                            (inner 3))))
                 (outer 2)))
       (vmA (compile-and-run exprA))
       (resultA (get-register vmA *reg-v0*)))
  (format t "Résultat: ~A (attendu: 6 = 2*3)~%" resultA)
  (if (= resultA 6)
      (format t "✓ TEST A OK~%")
      (format t "✗ TEST A ÉCHEC~%")))

;; Test B: Deux fonctions imbriquées, une seule appelée
(format t "~%Test B: (labels ((outer (x) (labels ((f1 (y) (* x y)) (f2 (y) (+ x y))) (f1 3)))) (outer 2))~%")
(let* ((exprB '(labels ((outer (x)
                          (labels ((f1 (y)
                                     (* x y))
                                   (f2 (y)
                                     (+ x y)))
                            (f1 3))))
                 (outer 2)))
       (vmB (compile-and-run exprB))
       (resultB (get-register vmB *reg-v0*)))
  (format t "Résultat: ~A (attendu: 6 = 2*3)~%" resultB)
  (if (= resultB 6)
      (format t "✓ TEST B OK~%")
      (format t "✗ TEST B ÉCHEC~%")))

;; Test C: Appel imbriqué simple
(format t "~%Test C: (labels ((outer (x) (labels ((double (y) (* x y)))) (double (double 3)))) (outer 2))~%")
(let* ((exprC '(labels ((outer (x)
                          (labels ((double (y)
                                     (* x y)))
                            (double (double 3)))))
                 (outer 2)))
       (vmC (compile-and-run exprC))
       (resultC (get-register vmC *reg-v0*)))
  (format t "Résultat: ~A (attendu: 12 = 2*(2*3))~%" resultC)
  (if (= resultC 12)
      (format t "✓ TEST C OK~%")
      (format t "✗ TEST C ÉCHEC~%")))

;; Test D: Le test problématique original simplifié
(format t "~%Test D: Version simplifiée du test 5~%")
(format t "(labels ((outer (factor)~%")
(format t "          (labels ((mult (n) (* factor n))~%")
(format t "                   (twice (n) (mult (mult n))))~%")
(format t "            (twice 3))))~%")
(format t "  (outer 2))~%")
(let* ((exprD '(labels ((outer (factor)
                          (labels ((mult (n)
                                     (* factor n))
                                   (twice (n)
                                     (mult (mult n))))
                            (twice 3))))
                 (outer 2)))
       (vmD (compile-and-run exprD))
       (resultD (get-register vmD *reg-v0*)))
  (format t "Résultat: ~A (attendu: 12 = 2*(2*3))~%" resultD)
  (if (= resultD 12)
      (format t "✓ TEST D OK~%")
      (format t "✗ TEST D ÉCHEC~%")))
